-- 나만의 블로그 — 블로그 DB (blog.db) ERD
-- 실제 DB는 SQLite입니다. ERD 도구(Crowfoot)에서 그리려고 server.py의 init_db() 결과를 PostgreSQL 문법으로 옮겼습니다.
-- 날짜·시각은 SQLite처럼 문자열(TEXT) 또는 epoch 초(BIGINT)로 둡니다. 정해진 값 목록은 앱(server.py)이 검사하므로 CHECK 대신 설명에 적었습니다.
-- [논리 FK]라고 적은 관계는 실제 DB에 FK 제약이 없고 앱이 지키는 관계입니다.
-- 회원 서버 DB(php-auth/db/sqlite.db)는 member-db.sql에 있습니다. 블로그 users.auth_uid가 회원 서버 users.id를 가리킵니다.
-- 기준: 2026-10-08

-- 블로그 회원: 회원 한 명 = 블로그 하나
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username        TEXT    NOT NULL,                    -- 블로그 주소 #/@아이디
    nickname        TEXT    NOT NULL,
    password_hash   TEXT    NOT NULL,                    -- PBKDF2-SHA256 10만 회 + 솔트. 관리자·예전 블로그 계정의 자체 로그인용
    role            TEXT    NOT NULL DEFAULT 'member',   -- admin 또는 member
    created_at      TEXT    NOT NULL,                    -- YYYY-MM-DDTHH:MM:SS
    watchlist       TEXT,                                -- 관심 종목 코드 JSON 목록
    auth_uid        BIGINT,                              -- 회원 서버 users.id. 관리자와 아직 연결하지 않은 예전 계정은 비어 있음
    room_bg         TEXT    NOT NULL DEFAULT 'room',     -- room·forest·beach·night·cafe·library
    room_char       TEXT    NOT NULL DEFAULT 'bear',     -- bear·cat·rabbit·penguin·dog·robot
    skin            TEXT    NOT NULL DEFAULT 'coral',    -- coral·blue·green·teal·purple·pink·mustard·ink
    hidden_widgets  TEXT    NOT NULL DEFAULT '[]',       -- 숨긴 사이드바 항목 JSON 목록(room·types·popular·tags·comments·stats)
    auth_joined     TEXT,                                -- 연결할 때 기억한 회원 서버 가입 시각(번호 재사용 가려내기)
    auth_nick_at    BIGINT  NOT NULL DEFAULT 0,          -- 회원 서버에서 닉네임을 바꾼 시각(epoch 초)
    blog_title      TEXT,
    blog_desc       TEXT,
    avatar          TEXT,                                -- /uploads/ 주소
    categories      TEXT,                                -- 카테고리 이름 JSON 목록(순서 포함)
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username)
);
CREATE UNIQUE INDEX idx_users_auth_uid ON users (auth_uid);

-- 글
CREATE TABLE posts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title       TEXT    NOT NULL,
    content     TEXT    NOT NULL DEFAULT '',             -- 마크다운, 최대 20만 자
    category    TEXT    NOT NULL DEFAULT '',             -- 글쓴이 users.categories 중 하나의 이름
    tags        TEXT    NOT NULL DEFAULT '',             -- 쉼표로 구분
    is_public   INTEGER NOT NULL DEFAULT 1,              -- 1 공개, 0 비공개
    views       BIGINT  NOT NULL DEFAULT 0,
    created_at  TEXT    NOT NULL,
    updated_at  TEXT    NOT NULL,
    type        TEXT    NOT NULL DEFAULT 'insight',      -- insight 인사이트·faq 자주 묻는 질문·glossary 용어 사전·daily 일상
    author_id   BIGINT,                                  -- 블로그 주인
    cover       TEXT    NOT NULL DEFAULT '',             -- 본문 사진 중 고른 /uploads/ 주소, 비면 첫 사진
    CONSTRAINT pk_posts PRIMARY KEY (id),
    CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES users (id)
);

-- 댓글: 답글은 parent_id로 1단계만
CREATE TABLE comments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    post_id        BIGINT  NOT NULL,
    name           TEXT    NOT NULL,                     -- 회원은 닉네임, 방문자는 적은 이름
    password_hash  TEXT    NOT NULL,                     -- 방문자 댓글의 삭제 비밀번호 해시
    content        TEXT    NOT NULL,
    created_at     TEXT    NOT NULL,
    user_id        BIGINT,                               -- 방문자 댓글은 비어 있음
    parent_id      BIGINT,                               -- 답글이면 원래 댓글
    deleted        INTEGER NOT NULL DEFAULT 0,           -- 1이면 "삭제된 댓글입니다" 자리로 남김
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_id) REFERENCES comments (id)
);

-- 공감: 한 글에 한 번
CREATE TABLE likes (
    post_id     BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    created_at  TEXT   NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (post_id, user_id),
    CONSTRAINT fk_likes_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE,
    CONSTRAINT fk_likes_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 이웃: 상대 승인 없이 한쪽 방향으로 추가
CREATE TABLE neighbors (
    user_id     BIGINT NOT NULL,                         -- 추가한 회원
    blog_id     BIGINT NOT NULL,                         -- 이웃으로 추가된 블로그 주인
    created_at  TEXT   NOT NULL,
    CONSTRAINT pk_neighbors PRIMARY KEY (user_id, blog_id),
    CONSTRAINT fk_neighbors_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_neighbors_blog FOREIGN KEY (blog_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX idx_neighbors_blog ON neighbors (blog_id);

-- 블로그 로그인 세션: 2주 유지
CREATE TABLE sessions (
    token    TEXT             NOT NULL,                  -- HttpOnly 쿠키 값
    user_id  BIGINT           NOT NULL,
    expires  DOUBLE PRECISION NOT NULL,                  -- epoch 초
    CONSTRAINT pk_sessions PRIMARY KEY (token),
    CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 올린 파일
CREATE TABLE files (
    stored_name    TEXT   NOT NULL,                      -- 무작위 이름, /uploads/ 아래
    original_name  TEXT   NOT NULL,
    size           BIGINT NOT NULL,                      -- 바이트
    user_id        BIGINT,
    created_at     TEXT   NOT NULL,
    CONSTRAINT pk_files PRIMARY KEY (stored_name),
    CONSTRAINT fk_files_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 블로그별 방문: 블로그마다 하루 한 번씩 센 방문자
CREATE TABLE blog_visits (
    day      TEXT   NOT NULL,                            -- YYYY-MM-DD
    blog_id  BIGINT NOT NULL,                            -- [논리 FK] 회원을 지울 때 함께 지움
    visitor  TEXT   NOT NULL,                            -- 방문자 쿠키(vid)
    CONSTRAINT pk_blog_visits PRIMARY KEY (day, blog_id, visitor),
    CONSTRAINT fk_blog_visits_blog FOREIGN KEY (blog_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 사이트 방문: 사이트 전체 하루 방문자(Today·Yesterday·Total)
CREATE TABLE visits (
    day      TEXT NOT NULL,                              -- YYYY-MM-DD
    visitor  TEXT NOT NULL,                              -- 방문자 쿠키(vid)
    CONSTRAINT pk_visits PRIMARY KEY (day, visitor)
);

-- 댓글 비밀번호 틀린 기록: 15분에 5번 틀리면 잠금
CREATE TABLE comment_pw_fails (
    comment_id  BIGINT NOT NULL,                         -- [논리 FK] 15분 지나면 지움
    ip          TEXT   NOT NULL,
    at          BIGINT NOT NULL,                         -- epoch 초
    CONSTRAINT fk_comment_pw_fails_comment FOREIGN KEY (comment_id) REFERENCES comments (id) ON DELETE CASCADE
);
CREATE INDEX idx_comment_pw_fails ON comment_pw_fails (comment_id, at);

-- 사이트 설정: 사이트 이름·회원가입 허용·맛집 API 키 등
CREATE TABLE settings (
    "key"  TEXT NOT NULL,
    value  TEXT,
    CONSTRAINT pk_settings PRIMARY KEY ("key")
);

-- 사용한 입장권: 회원 서버가 준 1회용 입장권(5분) 재사용 막기
CREATE TABLE sso_nonces (
    nonce    TEXT   NOT NULL,
    expires  BIGINT NOT NULL,                            -- epoch 초
    CONSTRAINT pk_sso_nonces PRIMARY KEY (nonce)
);

-- 논리명
COMMENT ON TABLE users IS '블로그 회원';
COMMENT ON COLUMN users.id IS '회원 번호';
COMMENT ON COLUMN users.username IS '아이디';
COMMENT ON COLUMN users.nickname IS '닉네임';
COMMENT ON COLUMN users.password_hash IS '비밀번호 해시';
COMMENT ON COLUMN users.role IS '역할';
COMMENT ON COLUMN users.created_at IS '가입 시각';
COMMENT ON COLUMN users.watchlist IS '관심 종목';
COMMENT ON COLUMN users.auth_uid IS '회원 서버 회원 번호';
COMMENT ON COLUMN users.room_bg IS '미니룸 배경';
COMMENT ON COLUMN users.room_char IS '미니룸 캐릭터';
COMMENT ON COLUMN users.skin IS '대표 색';
COMMENT ON COLUMN users.hidden_widgets IS '숨긴 사이드바 항목';
COMMENT ON COLUMN users.auth_joined IS '회원 서버 가입 시각';
COMMENT ON COLUMN users.auth_nick_at IS '닉네임 동기화 시각';
COMMENT ON COLUMN users.blog_title IS '블로그 이름';
COMMENT ON COLUMN users.blog_desc IS '블로그 소개';
COMMENT ON COLUMN users.avatar IS '프로필 사진';
COMMENT ON COLUMN users.categories IS '카테고리 목록';

COMMENT ON TABLE posts IS '글';
COMMENT ON COLUMN posts.id IS '글 번호';
COMMENT ON COLUMN posts.title IS '제목';
COMMENT ON COLUMN posts.content IS '본문';
COMMENT ON COLUMN posts.category IS '카테고리';
COMMENT ON COLUMN posts.tags IS '태그';
COMMENT ON COLUMN posts.is_public IS '공개 여부';
COMMENT ON COLUMN posts.views IS '조회수';
COMMENT ON COLUMN posts.created_at IS '작성 시각';
COMMENT ON COLUMN posts.updated_at IS '수정 시각';
COMMENT ON COLUMN posts.type IS '글 종류';
COMMENT ON COLUMN posts.author_id IS '글쓴이';
COMMENT ON COLUMN posts.cover IS '대표 사진';

COMMENT ON TABLE comments IS '댓글';
COMMENT ON COLUMN comments.id IS '댓글 번호';
COMMENT ON COLUMN comments.post_id IS '글 번호';
COMMENT ON COLUMN comments.name IS '이름';
COMMENT ON COLUMN comments.password_hash IS '삭제 비밀번호 해시';
COMMENT ON COLUMN comments.content IS '내용';
COMMENT ON COLUMN comments.created_at IS '작성 시각';
COMMENT ON COLUMN comments.user_id IS '회원 번호';
COMMENT ON COLUMN comments.parent_id IS '부모 댓글 번호';
COMMENT ON COLUMN comments.deleted IS '삭제 표시';

COMMENT ON TABLE likes IS '공감';
COMMENT ON COLUMN likes.post_id IS '글 번호';
COMMENT ON COLUMN likes.user_id IS '공감한 회원';
COMMENT ON COLUMN likes.created_at IS '공감한 시각';

COMMENT ON TABLE neighbors IS '이웃';
COMMENT ON COLUMN neighbors.user_id IS '추가한 회원';
COMMENT ON COLUMN neighbors.blog_id IS '이웃 블로그';
COMMENT ON COLUMN neighbors.created_at IS '추가한 시각';

COMMENT ON TABLE sessions IS '블로그 로그인 세션';
COMMENT ON COLUMN sessions.token IS '세션 토큰';
COMMENT ON COLUMN sessions.user_id IS '회원 번호';
COMMENT ON COLUMN sessions.expires IS '만료 시각';

COMMENT ON TABLE files IS '올린 파일';
COMMENT ON COLUMN files.stored_name IS '저장 이름';
COMMENT ON COLUMN files.original_name IS '원래 파일 이름';
COMMENT ON COLUMN files.size IS '크기';
COMMENT ON COLUMN files.user_id IS '올린 회원';
COMMENT ON COLUMN files.created_at IS '올린 시각';

COMMENT ON TABLE blog_visits IS '블로그별 방문';
COMMENT ON COLUMN blog_visits.day IS '날짜';
COMMENT ON COLUMN blog_visits.blog_id IS '블로그 주인';
COMMENT ON COLUMN blog_visits.visitor IS '방문자';

COMMENT ON TABLE visits IS '사이트 방문';
COMMENT ON COLUMN visits.day IS '날짜';
COMMENT ON COLUMN visits.visitor IS '방문자';

COMMENT ON TABLE comment_pw_fails IS '댓글 비밀번호 틀린 기록';
COMMENT ON COLUMN comment_pw_fails.comment_id IS '댓글 번호';
COMMENT ON COLUMN comment_pw_fails.ip IS 'IP';
COMMENT ON COLUMN comment_pw_fails.at IS '틀린 시각';

COMMENT ON TABLE settings IS '사이트 설정';
COMMENT ON COLUMN settings."key" IS '설정 이름';
COMMENT ON COLUMN settings.value IS '값';

COMMENT ON TABLE sso_nonces IS '사용한 입장권';
COMMENT ON COLUMN sso_nonces.nonce IS '입장권 번호';
COMMENT ON COLUMN sso_nonces.expires IS '만료 시각';
