-- 나만의 블로그 — 회원 서버 DB (php-auth/db/sqlite.db) ERD
-- 실제 DB는 SQLite입니다. ERD 도구(Crowfoot)에서 그리려고 php-auth/src/db.php의 db() 결과를 PostgreSQL 문법으로 옮겼습니다.
-- 시각은 SQLite처럼 문자열(TEXT) 또는 epoch 초(BIGINT)로 둡니다.
-- 블로그 DB(blog.db)는 blog-db.sql에 있습니다. 블로그 users.auth_uid가 이 DB의 users.id를 가리킵니다.
-- 기준: 2026-10-08

-- 회원: 회원가입·로그인을 맡는 회원 서버의 계정
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username       TEXT    NOT NULL,                     -- 대소문자 구분 없이 하나만(SQLite COLLATE NOCASE)
    password_hash  TEXT    NOT NULL,                     -- bcrypt
    nickname       TEXT    NOT NULL,
    bio            TEXT    NOT NULL DEFAULT '',          -- 처음 블로그를 만들 때 블로그 소개가 됨
    created_at     TEXT    NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
    session_ver    INTEGER NOT NULL DEFAULT 0,           -- 올리면 이전 로그인이 모두 끊김
    nickname_at    BIGINT  NOT NULL DEFAULT 0,           -- 닉네임을 바꾼 시각(epoch 초)
    CONSTRAINT pk_users PRIMARY KEY (id)
);
-- SQLite의 username UNIQUE COLLATE NOCASE(대소문자 구분 없이 하나만)를 식 인덱스로 옮김
CREATE UNIQUE INDEX uk_users_username_nocase ON users (lower(username));

-- SNS 연결: 카카오·네이버·구글 계정과 회원 연결
CREATE TABLE social_accounts (
    provider      TEXT   NOT NULL,                       -- kakao·naver·google
    provider_uid  TEXT   NOT NULL,
    user_id       BIGINT NOT NULL,
    created_at    TEXT   NOT NULL DEFAULT to_char(LOCALTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'),
    CONSTRAINT pk_social_accounts PRIMARY KEY (provider, provider_uid),
    CONSTRAINT uk_social_accounts_user_provider UNIQUE (user_id, provider),
    CONSTRAINT fk_social_accounts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 로그인 실패 기록: 비밀번호 무차별 대입 막기
CREATE TABLE login_attempts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username    TEXT   NOT NULL,                         -- 대소문자 구분 없이 셈
    ip          TEXT   NOT NULL,
    created_at  BIGINT NOT NULL,                         -- epoch 초
    CONSTRAINT pk_login_attempts PRIMARY KEY (id)
);
CREATE INDEX idx_attempts ON login_attempts (username, ip, created_at);

-- 가입 기록: IP별·사이트 전체 가입 횟수 제한과 자동 가입 막기
CREATE TABLE signup_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ip          TEXT   NOT NULL,
    kind        TEXT   NOT NULL,                         -- ok 가입됨, bot 자동 가입 의심
    created_at  BIGINT NOT NULL,                         -- epoch 초
    CONSTRAINT pk_signup_log PRIMARY KEY (id)
);
CREATE INDEX idx_signup_kind ON signup_log (kind, created_at);
CREATE INDEX idx_signup_ip ON signup_log (ip, kind, created_at);

-- 사용한 서명 표: 블로그가 보낸 1회용 표(로그아웃 등) 재사용 막기
CREATE TABLE sso_used_nonces (
    nonce    TEXT   NOT NULL,
    expires  BIGINT NOT NULL,                            -- epoch 초
    CONSTRAINT pk_sso_used_nonces PRIMARY KEY (nonce)
);

-- 블로그 상태 캐시: 블로그의 회원가입 허용 여부를 잠시 저장
CREATE TABLE bridge_cache (
    "key"       TEXT   NOT NULL,                         -- signup
    value       TEXT   NOT NULL,
    fetched_at  BIGINT NOT NULL,                         -- epoch 초
    CONSTRAINT pk_bridge_cache PRIMARY KEY ("key")
);

-- 논리명
COMMENT ON TABLE users IS '회원';
COMMENT ON COLUMN users.id IS '회원 번호';
COMMENT ON COLUMN users.username IS '아이디';
COMMENT ON COLUMN users.password_hash IS '비밀번호 해시';
COMMENT ON COLUMN users.nickname IS '닉네임';
COMMENT ON COLUMN users.bio IS '자기소개';
COMMENT ON COLUMN users.created_at IS '가입 시각';
COMMENT ON COLUMN users.session_ver IS '세션 버전';
COMMENT ON COLUMN users.nickname_at IS '닉네임 바꾼 시각';

COMMENT ON TABLE social_accounts IS 'SNS 연결';
COMMENT ON COLUMN social_accounts.provider IS 'SNS 종류';
COMMENT ON COLUMN social_accounts.provider_uid IS 'SNS 회원 번호';
COMMENT ON COLUMN social_accounts.user_id IS '회원 번호';
COMMENT ON COLUMN social_accounts.created_at IS '연결한 시각';

COMMENT ON TABLE login_attempts IS '로그인 실패 기록';
COMMENT ON COLUMN login_attempts.id IS '번호';
COMMENT ON COLUMN login_attempts.username IS '아이디';
COMMENT ON COLUMN login_attempts.ip IS 'IP';
COMMENT ON COLUMN login_attempts.created_at IS '시각';

COMMENT ON TABLE signup_log IS '가입 기록';
COMMENT ON COLUMN signup_log.id IS '번호';
COMMENT ON COLUMN signup_log.ip IS 'IP';
COMMENT ON COLUMN signup_log.kind IS '결과';
COMMENT ON COLUMN signup_log.created_at IS '시각';

COMMENT ON TABLE sso_used_nonces IS '사용한 서명 표';
COMMENT ON COLUMN sso_used_nonces.nonce IS '표 번호';
COMMENT ON COLUMN sso_used_nonces.expires IS '만료 시각';

COMMENT ON TABLE bridge_cache IS '블로그 상태 캐시';
COMMENT ON COLUMN bridge_cache."key" IS '항목';
COMMENT ON COLUMN bridge_cache.value IS '값';
COMMENT ON COLUMN bridge_cache.fetched_at IS '가져온 시각';
